# Generated by Django 2.2.4 on 2020-12-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('money', models.IntegerField(verbose_name='희망금액')),
                ('product', models.CharField(max_length=20, verbose_name='상품')),
                ('job', models.CharField(max_length=20, verbose_name='직업')),
                ('title', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='글제목')),
                ('text', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='글내용')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('region_1', models.CharField(max_length=20, verbose_name='시/도')),
                ('region_2', models.CharField(max_length=20, verbose_name='구/군')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='날짜')),
                ('clicks', models.IntegerField(default=1, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '문의글',
                'verbose_name_plural': '문의글',
                'db_table': 'information_postss',
            },
        ),
    ]
