# Generated by Django 2.2.4 on 2020-11-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=5000)),
                ('phone_number', models.CharField(max_length=20)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('clicks', models.IntegerField(default=1)),
                ('file_1', models.FileField(blank=True, null=True, upload_to='files/')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='files/')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='files/')),
                ('file_4', models.FileField(blank=True, null=True, upload_to='files/')),
                ('file_5', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
            options={
                'db_table': 'information_posts',
            },
        ),
    ]
