# Generated by Django 2.2.4 on 2020-12-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='글제목'),
        ),
    ]
